version: "3.7"

services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    environment:
      MONGODB_URI: mongodb://root:root@database:27017/admin
    entrypoint:
      - npm
      - run
      - dev
    depends_on:
      - database
  database:
    image: mongo:3.6-xenial
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongo-data:
    external: true