version: "3.7"

services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/app
    environment:
      APP_ENV: docker
      NODE_ENV: development
      MONGODB_URI: mongodb://root:root@database:27017/admin
      JWT_SECRET_KEY_TOKEN: abc123
      REACT_SENTRY_DSN: abc123
      LIVERELOAD_PORT: 32000
    entrypoint: /entrypoint.sh
    depends_on:
      - database
  database:
    image: mongo:3.6-xenial
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongo-data:
